/**
 * Profdiff web-app API
 *
 * Contact: jirkadanek@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Metadata from the profiler JSON file, if not found then null.
 */
export interface ProfileMetadata {
  /**
   * Kind of compilation for Java source code used by GraalVM compiler.
   */
  compilationKind?: string;
  /**
   * Total time sampling period of the profiler run.
   */
  totalPeriod?: number;
}
