/**
 * Profdiff web-app API
 *
 * Contact: jirkadanek@icloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The primary content to render (represents the only state for IDENTITY, INSERT, DELETE, and the NEW state for RELABEL).
 */
export interface RenderedTreeNodeNodeContent {
  /**
   * Action prefix, e.g. (inlined), (direct), or Optimization Phase...
   */
  action?: string;
  /**
   * The target method name, if applicable.
   */
  methodName?: string;
  /**
   * The BCI or BCI trace string.
   */
  bci?: string;
  /**
   * Additional property details (like \'with {peelings: 1}\').
   */
  additionalInfo?: string;
  /**
   * Raw fallback text if parsing fails or for INFO nodes.
   */
  rawText?: string;
}
